### ISSUE TITLE
Add link-check linter

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyverse.org#216]
@jimhester, did you mention the existence of something like this once?

**Comment by jimhester** [comment]
Yeah, docs.travis-ci.org uses https://github.com/gjtorikian/html-proofer to do this.

**Comment by jimhester** [comment]
There is some documentation on using it with travis at https://github.com/gjtorikian/html-proofer/wiki/Using-HTMLProofer-From-Ruby-and-Travis

**Comment by jimhester** [comment]
If we wanted to do this we could probably just do the 'stupid thing' they have on there

```yaml
language: ruby
before_install:
 - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
script:
 - gem install html-proofer && htmlproofer .
```

**Comment by batpigandme** [comment]
Great.

There's also the rakefile option:
```ruby
desc "Run the HTML-Proofer"
task :run_proofer do
  require 'html-proofer'


  # Ignore platform switcher hash URLs
  platform_hash_urls = ['#platform-mac', '#platform-windows', '#platform-linux', '#platform-all']
  HTMLProofer.check_directory("./output", {
    :url_ignore => platform_hash_urls,
    :typhoeus => { :ssl_verifypeer => false }
  }).run
end
```
https://github.com/atom/flight-manual.atom.io/blob/e6fa143f745fbd4908933e2ba67615eac8b24cff/Rakefile#L30-L40

**Comment by hadley** [comment]
Might be worth looking if there's a pre-made github action for this

**Comment by jimhester** [comment]
There seem to be a few, e.g. https://github.com/marketplace/actions/link-checker, https://github.com/gaurav-nelson/github-action-markdown-link-check,

**Comment by jimhester** [comment]
After trying them out locally it seems really easy to hit the GitHub rate limits and start getting 429 responses from GitHub. We would probably have to be careful to only check modified files and maybe even find a link checker (or make one) that uses a GITHUB_PAT to up the rate limit.

**Comment by maelle** [comment]
Sharing my experience in case it can be useful: I've just added two workflows to R-hub docs depending on https://github.com/urlstechie/urlchecker-action that I've found out about on a blog. It's quite new but the maintainers are very responsive. It uses a Python library that uses regex, not commonmark :cry: but that's because it's general to any file (Rd files? :slightly_smiling_face:).

* [workflow running monthly checking all files](https://github.com/r-hub/docs/blob/master/.github/workflows/urlchecks.yml)

* [workflow running when a label "needs-url-checks" is applied to a PR](https://github.com/r-hub/docs/blob/master/.github/workflows/pr.yml) It creates a [check run magically](https://github.com/r-hub/docs/pull/24). I used the GitHub API to find the files that had been modified. However, that means only 30 filenames would appear (an alternative would be to use the checkout action for all branches or so, and git diff + git merge-base).

**Comment by jimhester** [comment]
Those are nice @maelle! I think we _should_ be able to 
1. Run a workflow only when posts happen, e.g. files change in a given directory
2. Run the checks only on the files that have changed

With something like this. (it definitely won't work as-is, but you hopefully get the idea)

```yaml
on:
  push:
    paths: content/blog/**/*.markdown
  check_links:
     run: |
        files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        run_checker $files
```
