### ISSUE TITLE
table styling with raw `knitr::kable()` tables

### ISSUE THREAD

**Issue by jimhester** [tidyverse/tidyverse.org#307]
The default table styling basically outputs tables without any padding or lines, it does not look great. Ideally this would give us nicer output of some kind.

```r
knitr::kable(mtcars)
```

**Comment by jimhester** [comment]
I ended up with this css for a decently styled table

```css
td,th {
  padding: 0.4em;
}
thead {
border-top: 1px solid #aaa;
border-bottom: 1px solid #aaa;
}
table {
margin-left: auto;
margin-right: auto;
border-bottom: 1px solid #aaa;
}
```
